version: "3"

services:
  mosquitto:
    image: eclipse-mosquitto:2.0.14-openssl
    restart: unless-stopped
    networks:
      - default
    volumes:
      - ./config:/mosquitto/config
      - ./data:/mosquitto/data
      - ./log:/mosquitto/log
    ports:
      - '8883:8883'
